### ISSUE TITLE
CC

### ISSUE THREAD

**Issue by jnxxx** [jnxxx/homeassistant-connectedcars_io#13]
Hej @Kjagd

Jeg har et par andre spørgsmål, som ikke relaterer sig til leads. Håber det er ok.
Super hvis du kan svare, men naturligvis ikke noget du skal bruge lang tid på.

1. **Brug af logo**
Tror du nogen hos Connected Cars vil have noget imod jeg uploader jeres logo til [Home Assistant Brands repo](https://github.com/home-assistant/brands)?  
Man skal ved et pull request angive at man har rettigheder til at bruge logoet, hvilket jeg selvsagt ikke har.
Jeg tror at andre rask væk uploader logoer de ikke har rettigheder til, men det gør jeg altså ikke.
Det bevirker to ting:
   - Logo fremkommer på integrationen i Home Assistant, fremfor et billede som ikke kunne loades.
   - Integrationen kan optages i HACS. Det er katalog af custom integrationer, og derved vil flere sandsynligvis finde den.
     Det er et krav for den kan optages. Og grundet navngivningen, skal det også være logoet man finder på [connectedcars.io](https://connectedcars.io/).
 
    
    
2. **Fuel issues**
Ved du om der er sket ændringer på `fuelPercentage` og `refuelEvents`?
På min egen bil oplever jeg at `fuelPercentage` siden februar har sagt 50% konstant. `fuelLevel` virker stadig fint.
Og i løbet af juni er den stoppet med at registrere `refuelEvents`.
Begge dele har fungeret tidligere. Og det lyder til på andre, at det stadig gør for dem. Men har ingen ide om omfang.
```
{
  "data": {
    "vehicle": {
      "id": "79334",
      "refuelEvents": [
        {
          "litersAfter": 42,
          "litersBefore": 9,
          "time": "2023-06-05T16:42:02.000Z"
        },
        {
          "litersAfter": 42,
          "litersBefore": 14,
          "time": "2023-04-05T19:23:58.000Z"
        }
      ],
      "fuelLevel": {
        "time": "2023-09-11T17:33:42.000Z",
        "liter": 34
      },
      "fuelPercentage": {
        "time": "2023-02-02T08:06:35.000Z",
        "percent": 50
      }
    }
  }
}
```
Der er tanket to gange siden.

3. **Kan man aflæse om bilen er låst?**
Det ser ud til der har været noget tidligere og man har permission "can_see_lock".
Er det mon helt fjernet? Eller blot mig som ikke forstår at spørge på den rigtige måde?

**Comment by Kjagd** [comment]
Hej, jeg prøver lige at svare så godt jeg kan :)

1) Her tror jeg lige at jeg skal prøve at spørge lidt rundt, håber jeg kan vende tilbage med noget brugbart!

2) Omkring liters vs percentage, så ved jeg at vi pt primært har data på liters, og kun et fåtal som får percentage. (Jeg kender ikke lige den præcise grund hvorfor, men generelt er det enten fordi bilen ikke understøtter det, eller at vi ikke endnu trækker det, eller fordi vi har vurderet at data'en er for dårlig).
Jeg kan se at vi har et igangværende issue med refueling events som lige er på trapperne til at blive løst, så jeg vil tro at det virker igen fra næste uge af.

3) Lock status er desværre ikke noget som virker og vi har ingen planer om det. I meget korte træk hænger det sammen med at for at lytte efter låse status ville vi være nødsaget til at holde vores device tændt selvom bilen var slukket og dermed risikere 12V dræn. Men det er rigtigt nok at det en gang har virket sådan nogenlunde, men det gav desværre for mange problemer :)

**Comment by jnxxx** [comment]
2. Procentværdien er egentlig sekundær, det var mere hvis det kunne være relateret til refuel event.
Jeg ved ikke om det er tilfældigt, men der dukkede i eftermiddags en refuel event op dateret 23. august.
Det kan godt passe det er den seneste.

3. ok. 🙂

**Comment by Kjagd** [comment]
Ja, vores lille refueling problem blev løst med tilbagevirkende kraft i går, så godt at det lyder til at virke igen :)

**Comment by mm98** [comment]
Nu vil jeg ikke hijacke denne tråd. Min refuelEvent er én event bagud 😅 Tankede for 2 dage siden, men milesSinceRefule 581km (før igår var den +1500 km). Det er mere blot en oplysninge, da jeg selv har en automation for dette.

**Comment by Kjagd** [comment]
@jnxxx Hej igen, så er der lidt nye i logo sagen. Hvis du vil skrive din mail her, eller blot skrive til mig på kj@connectedcars.dk så kan jeg lige sende noget du kan bruge.
