### ISSUE TITLE
Opdateringshastighed af geolocation

### ISSUE THREAD

**Issue by joddershede** [jnxxx/homeassistant-connectedcars_io#16]
Halløj, jeg bruger med stor glæde integrationen.. er der nogen måde at skrue op på opdateringshastigheden på geolocation? Fx bare ned til 30 sek I stedet for 1 min? 
Jeg bruger den til at tænde for et par forskellige lys og formodentlig også en port i fremtiden inden bilen rammer matriklen, men enkelte gange skal jeg lige vente på den registrerer mig indenfor en zone.. jeg kunne self bare øge zonen, men hvis der nu var en oplagt ændring i denne integration ville jeg gerne skrue på den her:-) 
Mvh

**Comment by jnxxx** [comment]
Hej.

Så vidt jeg husker opdaterer den hver 60 sekunder når den har detekteret tænding, ellers 300 sekunder.
Jeg overvejede på et tidspunkt at gøre det konfigurerbart, men har valgt ikke at gøre det.

Vi skal huske på at vi har API'et stillet frit til rådighed. (I hvert fald uden at skulle betale for det direkte).
I håb om bevare det således forsøger jeg at belaste det mindst muligt, men stadig brugbar.

Hvis du insisterer kan du rette i koden i din egen instans.

**Comment by jnxxx** [comment]
Der er i `minvw.py`.
Den cacher de læste data en vis tid.
