### ISSUE TITLE
Failed to add custom repository

### ISSUE THREAD

**Issue by MarLoe** [jnxxx/homeassistant-connectedcars_io#18]
I have installed the latest HAOS v11.2. When trying to add this repository, it fails with the error message:

`2023-12-07 13:16:22.338 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /store/repositories - https://github.com/jnxxx/homeassistant-connectedcars_io is not a valid add-on repository`

What am I doing wrong, or do I have to revert to manual installation?

**Comment by mm98** [comment]
I just tried to readd my repository and it worked without any problems.

![image](https://github.com/jnxxx/homeassistant-connectedcars_io/assets/992714/63ca5ef7-80e8-4141-8379-dd159259e4cd)

```
Repository : https://github.com/jnxxx/homeassistant-connectedcars_io
Category   : Integration
```
