### ISSUE TITLE
Fuel percentage 

### ISSUE THREAD

**Issue by westfrost** [jnxxx/homeassistant-connectedcars_io#19]
Hey, skide fed integration!
Men kan se at fuelpercentage er en drillepind ved flere, men er der en måde jeg kan fixe det på? Den står altid på 100%, uanset liter.

**Comment by jnxxx** [comment]
Tak!
Det er et tal der kommer fra Connectedcars API'et.
For min egen bil viser den altid 50%, mens jeg har set for andre at der stadig kommer en relevant værdi.
Min virkede oprindeligt, men er frossen fast siden 2/2 i år.

Hvis du selv vil 'fikse' det, kan du lave en template sensor og beregne det ud fra fuel level i liter.
Du skal vide hvor stor tanken er, eller blot hvad fuellevel siger når tanken er fuld.
F.eks.:
`{{ states('sensor.volkswagen_polo_fuellevel') | float(0) / 42 * 100 }}`

`sensor.volkswagen_polo_fuellevel` skal du naturligvis rette så den passer med din fuellevel sensor, og 42 er det som den viser når tanken er fuld.
Der er ingen afrunding, det kan du gøre bagefter med display precision. I alle tilfælde bliver den ikke mere præcis end det fuellevel tillader, da det er en integer.

Template sensors lavede man før i tiden i configuration filen, det ved jeg ikke man man stadig kan.
I dag kan det laves i UI under Helpers.

**Comment by westfrost** [comment]
Hej!
Tusind tak for svaret, jeg prøver om jeg ikke kan få det til at virke med en template sensor.


________________________________
