### ISSUE TITLE
Recent data?

### ISSUE THREAD

**Issue by danielklejnstrup** [jnxxx/homeassistant-connectedcars_io#21]
Jeg har et par gange, i løbet af et par måneder, været ude for at dataene fra connectedcars.io har været forældede - i ét tilfælde flere dage, hvor VW bekræftede at der var knas i teknikken.
Ville det give mening at integrere et heartbeat timestamp, for hvornår der sidst er modtaget ændringer fra bilen?
Indtil jeg fandt din integration, brugte jeg Node-RED, til at kalde connectedcars.io, og give mig de ønskede data. Her hentede jeg bl.a. timestamp for følgende:

        chargePercentage {
          pct
          time
        }
        rangeTotalKm {
          km
          time
        }
        ignition {
          time
          on
        }
        position {
          latitude
          longitude
          direction
          time
        }

Deraf kunne jeg vælge det nyeste timestamp, og dermed vide hvornår bilen sidst var "set".

**Comment by jnxxx** [comment]
Du kan nu prøve [v1.1.3](https://github.com/jnxxx/homeassistant-connectedcars_io/releases/tag/v1.1.3).
Der er tilføjet en ekstra attribut på flere an sensorene med opdateringstidspunkt.

Desuden har jeg forsøgt at lave en sensor med rangeTotalKm.
Men den rapporteres ikke på min bil, så jeg kan ikke teste om det virker.

**Comment by jnxxx** [comment]
v1.1.3 er nu blevet released.
