### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by koburg** [jnxxx/homeassistant-connectedcars_io#4]
when adding the integration I type my credentials as described.
but nothing happen no car show up also tried restart.

`Denne fejl stammer fra en brugerdefineret integration.

Logger: custom_components.connectedcars_io.sensor
Source: custom_components/connectedcars_io/sensor.py:67 
Integration: Connectedcars.io (Min Volkswagen) (documentation, issues) 
First occurred: 06.20.13 (5 occurrences) 
Last logged: 06.24.56

Failed to add sensors: 'data'`

`Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:269 
Integration: Sensor (documentation, issues) 
First occurred: 06.20.13 (1 occurrences) 
Last logged: 06.20.13

Platform connectedcars_io not ready yet: None; Retrying in background in 30 seconds`

**Comment by jnxxx** [comment]
Please try to enable [debug logging](https://github.com/jnxxx/homeassistant-connectedcars_io#debugging) and restart, then it should write some more details in the log that will be helpful to determine what the problem is.

**Comment by koburg** [comment]
I did this like in your readme file. 

but I reinstalled and retyped password now it is showing data.
