### ISSUE TITLE
Location not updated after short trips

### ISSUE THREAD

**Issue by brianravn** [jnxxx/homeassistant-connectedcars_io#7]
After update to v.1.0.1, location is not updated after short trips (0-5 minutes). I suspect it is because Ignition is never true. It always takes several minutes until Ignition is true after I turn on my car.

**Comment by jnxxx** [comment]
Yes, it makes sense it will do that.
Try preview v1.0.2 and see if that is better.

**Comment by brianravn** [comment]
Thanks. I have updated to v.1.0.2. I will let you know how it is. 

Thank you for making the integration.

**Comment by brianravn** [comment]
It is working as expected now.
